<?php

namespace Database\Seeders;

use App\Models\IndonesianFood;
use Illuminate\Database\Seeder;

class IndonesianFoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Nutrients are standardized per 100g serving size based on TKPI (Kemenkes RI).
     */
    public function run(): void
    {
        $foods = [
            // Makanan Pokok
            [
                'name' => 'Nasi Putih',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 130,
                'protein' => 2.4,
                'carbs' => 28.6,
                'fat' => 0.3,
                'source' => 'TKPI Kemenkes',
                'description' => 'Nasi beras putih masak/tanak (1 porsi sedang ±150-200g)',
            ],
            [
                'name' => 'Nasi Merah',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 110,
                'protein' => 2.6,
                'carbs' => 22.8,
                'fat' => 0.9,
                'source' => 'TKPI Kemenkes',
                'description' => 'Nasi beras merah tanak, tinggi serat & indeks glikemik lebih rendah',
            ],
            [
                'name' => 'Nasi Uduk',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 160,
                'protein' => 3.1,
                'carbs' => 27.5,
                'fat' => 4.2,
                'source' => 'TKPI Kemenkes',
                'description' => 'Nasi gurih dimasak santan dan rempah serai pandan',
            ],
            [
                'name' => 'Lontong / Ketupat',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 144,
                'protein' => 2.7,
                'carbs' => 31.8,
                'fat' => 0.2,
                'source' => 'TKPI Kemenkes',
                'description' => 'Beras rebus padat dibungkus daun pisang/janur',
            ],
            [
                'name' => 'Bubur Ayam (Tanpa Topping)',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 75,
                'protein' => 1.8,
                'carbs' => 14.5,
                'fat' => 1.1,
                'source' => 'TKPI Kemenkes',
                'description' => 'Bubur beras lembut gurih berkaldu',
            ],
            [
                'name' => 'Mie Goreng Spesial',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 195,
                'protein' => 4.5,
                'carbs' => 26.2,
                'fat' => 8.1,
                'source' => 'TKPI Kemenkes',
                'description' => 'Mie kuning tumis kecap dengan telur dan sayur',
            ],
            [
                'name' => 'Kentang Rebus',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 87,
                'protein' => 1.9,
                'carbs' => 20.1,
                'fat' => 0.1,
                'source' => 'TKPI Kemenkes',
                'description' => 'Karbohidrat kompleks rendah kalori & mengenyangkan',
            ],

            // Lauk Pauk (Protein & Lemak)
            [
                'name' => 'Ayam Goreng Lengkuas',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 260,
                'protein' => 24.6,
                'carbs' => 2.5,
                'fat' => 16.5,
                'source' => 'TKPI Kemenkes',
                'description' => 'Potongan ayam dibumbui rempah lengkuas dan digoreng gurih',
            ],
            [
                'name' => 'Ayam Bakar Madu / Kecap',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 190,
                'protein' => 26.0,
                'carbs' => 4.5,
                'fat' => 7.5,
                'source' => 'TKPI Kemenkes',
                'description' => 'Ayam bakar rempah kecap manis, lemak lebih rendah dibanding goreng',
            ],
            [
                'name' => 'Dada Ayam Rebus / Kukus',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 165,
                'protein' => 31.0,
                'carbs' => 0.0,
                'fat' => 3.6,
                'source' => 'TKPI Kemenkes',
                'description' => 'Pilihan protein lean terbaik untuk muscle gain & defisit kalori',
            ],
            [
                'name' => 'Rendang Sapi',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 285,
                'protein' => 22.5,
                'carbs' => 5.2,
                'fat' => 19.3,
                'source' => 'TKPI Kemenkes',
                'description' => 'Daging sapi olahan santan karamelisasi khas Minangkabau',
            ],
            [
                'name' => 'Sate Ayam (Daging Saja)',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 180,
                'protein' => 23.8,
                'carbs' => 3.2,
                'fat' => 8.1,
                'source' => 'TKPI Kemenkes',
                'description' => 'Sate daging ayam bakar tanpa bumbu kacang pekat (±4-5 tusuk per 100g)',
            ],
            [
                'name' => 'Bumbu Kacang Sate',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 50,
                'serving_unit' => 'g',
                'calories' => 135,
                'protein' => 4.5,
                'carbs' => 8.2,
                'fat' => 10.2,
                'source' => 'TKPI Kemenkes',
                'description' => 'Saus kacang tanah kental kecap (1 porsi saus ±50g)',
            ],
            [
                'name' => 'Telur Ayam Rebus',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 55,
                'serving_unit' => 'butir',
                'calories' => 78,
                'protein' => 6.3,
                'carbs' => 0.6,
                'fat' => 5.3,
                'source' => 'TKPI Kemenkes',
                'description' => '1 butir telur ayam utuh rebus (±55g)',
            ],
            [
                'name' => 'Telur Ceplok Goreng',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 60,
                'serving_unit' => 'butir',
                'calories' => 110,
                'protein' => 6.3,
                'carbs' => 0.7,
                'fat' => 9.2,
                'source' => 'TKPI Kemenkes',
                'description' => '1 butir telur digoreng minyak (mata sapi)',
            ],
            [
                'name' => 'Telur Balado',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 75,
                'serving_unit' => 'butir',
                'calories' => 135,
                'protein' => 6.8,
                'carbs' => 3.5,
                'fat' => 10.2,
                'source' => 'TKPI Kemenkes',
                'description' => '1 butir telur rebus goreng dengan baluran sambal balado',
            ],
            [
                'name' => 'Tempe Goreng Tepung / Mendoan',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 50,
                'serving_unit' => 'potong',
                'calories' => 130,
                'protein' => 5.5,
                'carbs' => 8.5,
                'fat' => 8.5,
                'source' => 'TKPI Kemenkes',
                'description' => '1 potong tempe dibalur adonan tepung terigu goreng gurih',
            ],
            [
                'name' => 'Tempe Bacem',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 50,
                'serving_unit' => 'potong',
                'calories' => 95,
                'protein' => 6.8,
                'carbs' => 7.2,
                'fat' => 4.2,
                'source' => 'TKPI Kemenkes',
                'description' => '1 potong tempe bumbu gula jawa ketumbar rebus/panggang',
            ],
            [
                'name' => 'Tahu Goreng',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 50,
                'serving_unit' => 'potong',
                'calories' => 85,
                'protein' => 5.0,
                'carbs' => 1.5,
                'fat' => 6.8,
                'source' => 'TKPI Kemenkes',
                'description' => '1 potong tahu kedelai goreng',
            ],
            [
                'name' => 'Ikan Nila / Mas Bakar',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 140,
                'protein' => 20.2,
                'carbs' => 2.1,
                'fat' => 5.4,
                'source' => 'TKPI Kemenkes',
                'description' => 'Ikan air tawar bakar bumbu rempah kecap',
            ],
            [
                'name' => 'Ikan Lele Goreng',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 240,
                'protein' => 18.7,
                'carbs' => 2.0,
                'fat' => 17.5,
                'source' => 'TKPI Kemenkes',
                'description' => 'Ikan lele goreng garing gurih',
            ],
            [
                'name' => 'Bakso Sapi Kuah (1 Porsi Komplit)',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 250,
                'serving_unit' => 'porsi',
                'calories' => 325,
                'protein' => 19.5,
                'carbs' => 28.0,
                'fat' => 14.5,
                'source' => 'TKPI Kemenkes',
                'description' => '5 butir bakso daging sapi, mie kuning/bihun, tahu bakso, kuah kaldu',
            ],
            [
                'name' => 'Soto Ayam Lamongan / Bening (1 Mangkok)',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 250,
                'serving_unit' => 'mangkok',
                'calories' => 210,
                'protein' => 18.0,
                'carbs' => 12.0,
                'fat' => 9.5,
                'source' => 'TKPI Kemenkes',
                'description' => 'Suwiran ayam, bihun, kubis, telur rebus separuh dalam kuah kunyit harum',
            ],

            // Sayuran & Sup
            [
                'name' => 'Sayur Asem',
                'category' => 'Sayuran',
                'serving_size_g' => 150,
                'serving_unit' => 'mangkok',
                'calories' => 65,
                'protein' => 2.5,
                'carbs' => 12.0,
                'fat' => 1.0,
                'source' => 'TKPI Kemenkes',
                'description' => 'Kacang panjang, labu siam, jagung manis, asam jawa segar',
            ],
            [
                'name' => 'Sayur Bening Bayam & Jagung',
                'category' => 'Sayuran',
                'serving_size_g' => 150,
                'serving_unit' => 'mangkok',
                'calories' => 45,
                'protein' => 2.8,
                'carbs' => 8.5,
                'fat' => 0.4,
                'source' => 'TKPI Kemenkes',
                'description' => 'Sayur bayam segar kuah kunci bening dan potongan jagung manis',
            ],
            [
                'name' => 'Tumis Kangkung Terasi',
                'category' => 'Sayuran',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 85,
                'protein' => 2.4,
                'carbs' => 5.2,
                'fat' => 6.2,
                'source' => 'TKPI Kemenkes',
                'description' => 'Kangkung tumis bawang dan cabai terasi',
            ],
            [
                'name' => 'Capcay Sayur Kuah/Goreng',
                'category' => 'Sayuran',
                'serving_size_g' => 150,
                'serving_unit' => 'porsi',
                'calories' => 110,
                'protein' => 4.5,
                'carbs' => 11.0,
                'fat' => 5.5,
                'source' => 'TKPI Kemenkes',
                'description' => 'Wortel, brokoli, kembang kol, sawi, jamur tumis gurih',
            ],
            [
                'name' => 'Gado-Gado Komplit',
                'category' => 'Sayuran',
                'serving_size_g' => 250,
                'serving_unit' => 'porsi',
                'calories' => 380,
                'protein' => 14.5,
                'carbs' => 36.0,
                'fat' => 20.5,
                'source' => 'TKPI Kemenkes',
                'description' => 'Sayur rebus, tempe, tahu, telur rebus dengan siraman saus kacang',
            ],
            [
                'name' => 'Sambal Terasi Uleg',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 20,
                'serving_unit' => 'sdm',
                'calories' => 30,
                'protein' => 0.8,
                'carbs' => 2.8,
                'fat' => 1.8,
                'source' => 'TKPI Kemenkes',
                'description' => 'Sambal cabai merah, rawit, terasi bakar, tomat dan perasan jeruk limau',
            ],

            // Padang Specialties & Pelengkap Nusantara
            [
                'name' => 'Ayam Pop',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'potong',
                'calories' => 215,
                'protein' => 22.0,
                'carbs' => 1.5,
                'fat' => 13.5,
                'source' => 'Calora curated estimate',
                'description' => 'Ayam kampung rebus air kelapa bawang putih lalu digoreng kilat',
            ],
            [
                'name' => 'Ayam Gulai Padang',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 120,
                'serving_unit' => 'potong',
                'calories' => 285,
                'protein' => 23.5,
                'carbs' => 3.2,
                'fat' => 20.0,
                'source' => 'Calora curated estimate',
                'description' => 'Potongan ayam dimasak kuah santan kuning rempah Minang',
            ],
            [
                'name' => 'Dendeng Balado Batokok',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 80,
                'serving_unit' => 'potong',
                'calories' => 265,
                'protein' => 25.0,
                'carbs' => 4.0,
                'fat' => 16.8,
                'source' => 'Calora curated estimate',
                'description' => 'Irisan daging sapi pipih goreng dengan lumuran cabai merah uleg kasar',
            ],
            [
                'name' => 'Gulai Tunjang / Kikil Padang',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'potong',
                'calories' => 240,
                'protein' => 19.5,
                'carbs' => 2.8,
                'fat' => 16.5,
                'source' => 'Calora curated estimate',
                'description' => 'Kikil kaki sapi empuk dalam kuah santan gulai pekat khas Minang',
            ],
            [
                'name' => 'Daun Singkong Rebus Padang',
                'category' => 'Sayuran',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 48,
                'protein' => 3.7,
                'carbs' => 7.5,
                'fat' => 0.6,
                'source' => 'Calora curated estimate',
                'description' => 'Pucuk daun singkong empuk rebus pendamping wajib Nasi Padang',
            ],
            [
                'name' => 'Gulai Cubadak (Nangka Muda Padang)',
                'category' => 'Sayuran',
                'serving_size_g' => 120,
                'serving_unit' => 'porsi',
                'calories' => 135,
                'protein' => 2.4,
                'carbs' => 14.0,
                'fat' => 8.2,
                'source' => 'Calora curated estimate',
                'description' => 'Gulai nangka muda khas Padang berkuah santan gurih beraroma rempah',
            ],
            [
                'name' => 'Sambal Ijo Padang (Lado Mudo)',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 30,
                'serving_unit' => 'sdm',
                'calories' => 45,
                'protein' => 0.7,
                'carbs' => 3.2,
                'fat' => 3.5,
                'source' => 'Calora curated estimate',
                'description' => 'Sambal cabai hijau besar kukus uleg kasar dengan minyak kelapa gurih',
            ],
            [
                'name' => 'Perkedel Kentang Padang',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 50,
                'serving_unit' => 'buah',
                'calories' => 115,
                'protein' => 3.2,
                'carbs' => 16.0,
                'fat' => 4.4,
                'source' => 'Calora curated estimate',
                'description' => 'Kentang tumbuk gurih berbalut telur goreng garing',
            ],

            // Jajanan & Camilan
            [
                'name' => 'Pisang Goreng',
                'category' => 'Jajanan & Camilan',
                'serving_size_g' => 70,
                'serving_unit' => 'buah',
                'calories' => 150,
                'protein' => 1.5,
                'carbs' => 24.0,
                'fat' => 5.5,
                'source' => 'TKPI Kemenkes',
                'description' => '1 buah pisang kepok/raja celup tepung goreng renyah',
            ],
            [
                'name' => 'Bakwan Sayur / Bala-Bala',
                'category' => 'Jajanan & Camilan',
                'serving_size_g' => 50,
                'serving_unit' => 'buah',
                'calories' => 135,
                'protein' => 2.2,
                'carbs' => 14.8,
                'fat' => 7.8,
                'source' => 'TKPI Kemenkes',
                'description' => '1 buah gorengan sayur kol wortel tepung',
            ],
            [
                'name' => 'Martabak Telur Daging (1 Potong)',
                'category' => 'Jajanan & Camilan',
                'serving_size_g' => 75,
                'serving_unit' => 'potong',
                'calories' => 195,
                'protein' => 7.5,
                'carbs' => 10.2,
                'fat' => 14.0,
                'source' => 'TKPI Kemenkes',
                'description' => '1 potong martabak kulit garing isi telur bebek, daging cincang, daun bawang',
            ],
            [
                'name' => 'Siomay Ikan Bandung (1 Buah)',
                'category' => 'Jajanan & Camilan',
                'serving_size_g' => 45,
                'serving_unit' => 'buah',
                'calories' => 75,
                'protein' => 4.2,
                'carbs' => 7.5,
                'fat' => 3.2,
                'source' => 'TKPI Kemenkes',
                'description' => '1 buah siomay kukus tenggiri kenyal gurih',
            ],
            [
                'name' => 'Pempek Kapal Selam Kecil (1 Buah)',
                'category' => 'Jajanan & Camilan',
                'serving_size_g' => 60,
                'serving_unit' => 'buah',
                'calories' => 110,
                'protein' => 5.8,
                'carbs' => 14.0,
                'fat' => 3.6,
                'source' => 'TKPI Kemenkes',
                'description' => '1 buah pempek isi telur rebus disajikan dengan kuah cuko',
            ],

            // Minuman
            [
                'name' => 'Air Kelapa Muda Murni',
                'category' => 'Minuman',
                'serving_size_g' => 250,
                'serving_unit' => 'gelas',
                'calories' => 45,
                'protein' => 0.5,
                'carbs' => 10.5,
                'fat' => 0.2,
                'source' => 'TKPI Kemenkes',
                'description' => 'Minuman elektrolit alami kaya kalium untuk rehidrasi pasca olahraga',
            ],
            [
                'name' => 'Es Teh Manis',
                'category' => 'Minuman',
                'serving_size_g' => 250,
                'serving_unit' => 'gelas',
                'calories' => 90,
                'protein' => 0.0,
                'carbs' => 22.5,
                'fat' => 0.0,
                'source' => 'TKPI Kemenkes',
                'description' => '1 gelas teh seduh dingin dengan 2 sendok makan gula',
            ],
            [
                'name' => 'Kopi Hitam Polos (Tanpa Gula)',
                'category' => 'Minuman',
                'serving_size_g' => 200,
                'serving_unit' => 'cangkir',
                'calories' => 4,
                'protein' => 0.3,
                'carbs' => 0.6,
                'fat' => 0.0,
                'source' => 'TKPI Kemenkes',
                'description' => 'Kopi hitam Americano/tubruk murni tanpa kalori tambahan',
            ],

            // Common Indonesian Foods - curated estimates pending official source import
            [
                'name' => 'Nasi Kuning',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 180,
                'serving_unit' => 'porsi',
                'calories' => 235,
                'protein' => 4.5,
                'carbs' => 45.0,
                'fat' => 4.0,
                'source' => 'Calora curated estimate',
                'description' => 'Nasi berbumbu kunyit dan santan ringan, tanpa lauk pelengkap',
            ],
            [
                'name' => 'Nasi Goreng Kampung',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 250,
                'serving_unit' => 'porsi',
                'calories' => 420,
                'protein' => 12.0,
                'carbs' => 60.0,
                'fat' => 14.0,
                'source' => 'Calora curated estimate',
                'description' => 'Nasi goreng dengan bumbu bawang, kecap, telur, dan sayuran sederhana',
            ],
            [
                'name' => 'Nasi Liwet',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 200,
                'serving_unit' => 'porsi',
                'calories' => 330,
                'protein' => 6.0,
                'carbs' => 55.0,
                'fat' => 10.0,
                'source' => 'Calora curated estimate',
                'description' => 'Nasi gurih berbumbu khas Sunda atau Solo tanpa lauk pelengkap',
            ],
            [
                'name' => 'Mie Ayam',
                'category' => 'Makanan Pokok',
                'serving_size_g' => 300,
                'serving_unit' => 'mangkuk',
                'calories' => 450,
                'protein' => 20.0,
                'carbs' => 55.0,
                'fat' => 16.0,
                'source' => 'Calora curated estimate',
                'description' => 'Mie telur dengan ayam kecap, sawi, dan kuah pendamping',
            ],
            [
                'name' => 'Opor Ayam',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 150,
                'serving_unit' => 'potong dengan kuah',
                'calories' => 310,
                'protein' => 25.0,
                'carbs' => 5.0,
                'fat' => 22.0,
                'source' => 'Calora curated estimate',
                'description' => 'Ayam masak kuah santan berbumbu kuning',
            ],
            [
                'name' => 'Rawon Daging',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 300,
                'serving_unit' => 'mangkuk',
                'calories' => 360,
                'protein' => 24.0,
                'carbs' => 12.0,
                'fat' => 24.0,
                'source' => 'Calora curated estimate',
                'description' => 'Sup daging sapi berkuah kluwek khas Jawa Timur',
            ],
            [
                'name' => 'Pepes Ikan',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'bungkus',
                'calories' => 150,
                'protein' => 22.0,
                'carbs' => 3.0,
                'fat' => 6.0,
                'source' => 'Calora curated estimate',
                'description' => 'Ikan berbumbu rempah yang dikukus dalam daun pisang',
            ],
            [
                'name' => 'Ikan Goreng',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'potong',
                'calories' => 230,
                'protein' => 22.0,
                'carbs' => 2.0,
                'fat' => 14.0,
                'source' => 'Calora curated estimate',
                'description' => 'Ikan goreng berbumbu sederhana, tanpa sambal pelengkap',
            ],
            [
                'name' => 'Tahu Bacem',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 75,
                'serving_unit' => 'potong',
                'calories' => 140,
                'protein' => 7.0,
                'carbs' => 11.0,
                'fat' => 7.0,
                'source' => 'Calora curated estimate',
                'description' => 'Tahu berbumbu gula merah dan rempah khas Jawa',
            ],
            [
                'name' => 'Tempe Goreng',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 50,
                'serving_unit' => 'potong',
                'calories' => 160,
                'protein' => 8.0,
                'carbs' => 8.0,
                'fat' => 11.0,
                'source' => 'Calora curated estimate',
                'description' => 'Tempe iris goreng dengan lapisan bumbu sederhana',
            ],
            [
                'name' => 'Udang Balado',
                'category' => 'Lauk Pauk',
                'serving_size_g' => 100,
                'serving_unit' => 'porsi',
                'calories' => 180,
                'protein' => 20.0,
                'carbs' => 5.0,
                'fat' => 8.0,
                'source' => 'Calora curated estimate',
                'description' => 'Udang tumis sambal balado dengan minyak secukupnya',
            ],
            [
                'name' => 'Sayur Lodeh',
                'category' => 'Sayuran',
                'serving_size_g' => 150,
                'serving_unit' => 'porsi',
                'calories' => 160,
                'protein' => 4.0,
                'carbs' => 10.0,
                'fat' => 11.0,
                'source' => 'Calora curated estimate',
                'description' => 'Sayuran campur berkuah santan ringan',
            ],
            [
                'name' => 'Urap Sayur',
                'category' => 'Sayuran',
                'serving_size_g' => 150,
                'serving_unit' => 'porsi',
                'calories' => 140,
                'protein' => 5.0,
                'carbs' => 12.0,
                'fat' => 8.0,
                'source' => 'Calora curated estimate',
                'description' => 'Sayuran rebus dengan kelapa berbumbu',
            ],
            [
                'name' => 'Pecel Sayur',
                'category' => 'Sayuran',
                'serving_size_g' => 200,
                'serving_unit' => 'porsi',
                'calories' => 220,
                'protein' => 8.0,
                'carbs' => 20.0,
                'fat' => 12.0,
                'source' => 'Calora curated estimate',
                'description' => 'Sayuran rebus dengan saus kacang',
            ],
            [
                'name' => 'Sop Ayam Sayur',
                'category' => 'Sayuran',
                'serving_size_g' => 300,
                'serving_unit' => 'mangkuk',
                'calories' => 210,
                'protein' => 22.0,
                'carbs' => 15.0,
                'fat' => 8.0,
                'source' => 'Calora curated estimate',
                'description' => 'Sup bening ayam dengan wortel, kentang, dan kol',
            ],
            [
                'name' => 'Martabak Manis',
                'category' => 'Jajanan & Camilan',
                'serving_size_g' => 100,
                'serving_unit' => 'g',
                'calories' => 300,
                'protein' => 6.0,
                'carbs' => 42.0,
                'fat' => 12.0,
                'source' => 'Calora curated estimate',
                'description' => 'Martabak manis dengan isian standar tanpa topping ekstra',
            ],
            [
                'name' => 'Risoles',
                'category' => 'Jajanan & Camilan',
                'serving_size_g' => 75,
                'serving_unit' => 'buah',
                'calories' => 180,
                'protein' => 4.0,
                'carbs' => 20.0,
                'fat' => 9.0,
                'source' => 'Calora curated estimate',
                'description' => 'Risoles goreng isi sayur dan ragout sederhana',
            ],
            [
                'name' => 'Lumpia Goreng',
                'category' => 'Jajanan & Camilan',
                'serving_size_g' => 75,
                'serving_unit' => 'buah',
                'calories' => 160,
                'protein' => 4.0,
                'carbs' => 17.0,
                'fat' => 8.0,
                'source' => 'Calora curated estimate',
                'description' => 'Lumpia goreng isi sayuran dan protein sederhana',
            ],
            [
                'name' => 'Es Jeruk Manis',
                'category' => 'Minuman',
                'serving_size_g' => 250,
                'serving_unit' => 'gelas',
                'calories' => 120,
                'protein' => 1.0,
                'carbs' => 29.0,
                'fat' => 0.0,
                'source' => 'Calora curated estimate',
                'description' => 'Minuman jeruk dengan gula tambahan',
            ],
            [
                'name' => 'Es Kopi Susu Gula Aren',
                'category' => 'Minuman',
                'serving_size_g' => 250,
                'serving_unit' => 'gelas',
                'calories' => 220,
                'protein' => 4.0,
                'carbs' => 32.0,
                'fat' => 8.0,
                'source' => 'Calora curated estimate',
                'description' => 'Kopi susu dingin dengan gula aren',
            ],
        ];

        foreach ($foods as $food) {
            IndonesianFood::updateOrCreate(
                ['name' => $food['name']],
                $food
            );
        }
    }
}
